import Link from "next/link";

export const metadata = { title: "Privacy Policy — PetAlyze" };

export default function PrivacyPage() {
  return <main className="container py-16">
    <Link href="/" className="font-bold text-[var(--green)]">← PetAlyze</Link>
    <article className="card mt-8 max-w-4xl p-8 md:p-10">
      <h1 className="text-4xl font-bold">Privacy Policy</h1>
      <p className="mt-3 text-sm text-[var(--muted)]">Effective: September 5, 2026</p>
      <div className="mt-8 space-y-8 leading-7 text-[var(--muted)]">
        <section><h2 className="text-xl font-bold text-[var(--ink)]">1. About this policy</h2><p className="mt-2">This Privacy Policy explains how PetAlyze processes information when you use our website and digital service. PetAlyze helps pet owners keep pet profiles, journals, passport information and media, and create AI-assisted stories, illustrations and comics.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">2. Information we process</h2><p className="mt-2">Depending on how you use PetAlyze, we may process account information such as your email address; pet profile and passport information you enter; journal entries; uploaded photos and other media; AI prompts, generation inputs and outputs; service usage and technical information; and subscription or transaction status when paid services become available.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">3. How we use information</h2><p className="mt-2">We use information to provide and secure the service, authenticate accounts, store the content you choose to save, generate requested AI content, maintain credits and subscription status, troubleshoot problems, prevent abuse, improve PetAlyze and communicate about service-related matters.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">4. AI processing</h2><p className="mt-2">When you request an AI feature, the text, images or other content needed for that request may be sent to third-party AI infrastructure providers so the requested output can be generated. Do not upload content you do not have the right to use, and avoid including unnecessary sensitive personal information in prompts or pet records.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">5. Service providers</h2><p className="mt-2">PetAlyze may use service providers for hosting, database and storage, authentication, AI processing, security, analytics, email and payment processing. They may process information only as needed to provide their services to PetAlyze and subject to their applicable terms and safeguards.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">6. Payments</h2><p className="mt-2">When paid subscriptions are activated, payments will be processed by a payment provider. PetAlyze does not need to store your full payment-card number when checkout is handled by the payment provider. We may receive transaction identifiers, payment status, amount, currency and subscription information needed to provide the purchased service.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">7. Storage and retention</h2><p className="mt-2">We retain information for as long as reasonably necessary to provide the service, maintain legitimate business and security records, resolve disputes and meet legal obligations. Retention periods can vary by data type. Account content may be removed or anonymized when it is no longer required, subject to backup and legal-retention needs.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">8. Your choices and rights</h2><p className="mt-2">Depending on applicable law, you may have rights to request access, correction, deletion, restriction, portability or other action regarding your personal information. You may also delete certain content directly where PetAlyze provides that function. Contact us to make a privacy request.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">9. Security</h2><p className="mt-2">We use reasonable technical and organizational measures designed to protect account and service data. No internet service can guarantee absolute security, so you should also protect your login credentials and device access.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">10. Children</h2><p className="mt-2">PetAlyze is not directed to children under 13, and we do not knowingly request personal information from children under 13. If you believe a child has provided personal information to us, please contact us.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">11. International processing</h2><p className="mt-2">Our service providers may process information in countries other than your own. Where required, we take appropriate steps for international transfers under applicable law.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">12. Changes</h2><p className="mt-2">We may update this policy as PetAlyze evolves. The effective date above identifies the current version. Material changes may also be communicated through the service where appropriate.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">13. Contact</h2><p className="mt-2">For privacy questions or requests, use our <Link href="/contact" className="font-semibold text-[var(--green)] underline">Contact page</Link>.</p></section>
      </div>
    </article>
  </main>;
}
