import Link from "next/link";
import SiteHeader from "@/components/site-header";
const features=[
["✦","AI Pet Insights","Turn everyday observations and photos into useful, easy-to-understand insights about your pet."],
["♡","Smart Journal","Keep milestones, notes, routines and memorable moments in one beautiful timeline."],
["▣","Digital Pet Passport","Store essential pet information, vaccinations, documents and important dates in one place."],
["◉","Memory Studio","Create stories, captions, memes and social-ready content from your favorite pet moments."],
["⌁","Photo Analysis","Organize pet photos and prepare them for future AI-powered recognition and analysis."],
["↗","Content & Monetization","Turn your pet's story into shareable content and build an audience around it."]
];
export default function Home(){
return <main><SiteHeader/>
<section className="hero-grid"><div className="container grid min-h-[650px] items-center gap-12 py-20 lg:grid-cols-[1.05fr_.95fr]">
<div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-white px-4 py-2 text-sm shadow-sm"><span className="text-[var(--green)]">●</span>A smarter life with your pet</div>
<h1 className="max-w-3xl text-5xl font-bold tracking-[-.04em] sm:text-6xl lg:text-7xl">Understand your pet better with <span className="text-[var(--green)]">AI.</span></h1>
<p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">PetAlyze brings your pet's memories, journal, digital passport and AI-powered content tools together in one simple place.</p>
<div className="mt-9 flex flex-wrap gap-3"><Link href="/signup" className="btn btn-primary px-7">Start free →</Link><Link href="/dashboard" className="btn btn-secondary px-7">Open demo dashboard</Link></div>
<div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-[var(--muted)]"><span>✓ Free plan</span><span>✓ No card required</span><span>✓ Built for pet lovers</span></div></div>
<div className="card mx-auto max-w-md p-5"><div className="rounded-3xl bg-[var(--cream)] p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">Today with</p><h2 className="mt-1 text-2xl font-bold">Luna 🐶</h2></div><span className="rounded-2xl bg-white px-3 py-2 text-sm">Healthy</span></div><div className="mt-6 flex h-52 items-center justify-center rounded-3xl bg-gradient-to-br from-emerald-100 via-white to-sky-100 text-8xl">🐕</div><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-2xl bg-white p-3"><p className="text-xs text-[var(--muted)]">Mood</p><b>Happy</b></div><div className="rounded-2xl bg-white p-3"><p className="text-xs text-[var(--muted)]">Walks</p><b>2 / 2</b></div><div className="rounded-2xl bg-white p-3"><p className="text-xs text-[var(--muted)]">Memories</p><b>128</b></div></div></div></div>
</div></section>
<section id="features" className="container py-24"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[var(--green)]">One pet. One story.</p><h2 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Everything your pet's digital life needs.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(([icon,title,text])=><article className="card p-7" key={title}><div className="paw">{icon}</div><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{text}</p></article>)}</div></section>
<section id="how" className="bg-[var(--cream)] py-24"><div className="container text-center"><p className="text-sm font-bold uppercase tracking-[.18em] text-[var(--green)]">How it works</p><h2 className="mt-3 text-4xl font-bold">Create. Remember. Understand.</h2><div className="mx-auto mt-12 grid max-w-5xl gap-5 md:grid-cols-3">{["Create your pet profile","Capture everyday moments","Turn memories into AI content"].map((x,i)=><div className="card p-7 text-left" key={x}><div className="text-sm font-bold text-[var(--green)]">0{i+1}</div><h3 className="mt-8 text-xl font-bold">{x}</h3></div>)}</div></div></section>
<section id="pricing" className="container py-24"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[.18em] text-[var(--green)]">Simple pricing</p><h2 className="mt-3 text-4xl font-bold">Start free. Upgrade when you need more.</h2></div><div className="mx-auto mt-12 grid max-w-4xl gap-6 md:grid-cols-2"><div className="card p-8"><p className="font-bold">Free</p><div className="mt-3 text-5xl font-bold">$0</div><ul className="mt-7 space-y-3 text-[var(--muted)]"><li>✓ 1 AI story / month</li><li>✓ Pet profile</li><li>✓ Smart journal</li><li>✓ Digital pet passport</li></ul><Link href="/signup" className="btn btn-secondary mt-8 w-full">Get started</Link></div><div className="card border-2 border-[var(--green)] p-8"><p className="font-bold">Premium</p><div className="mt-3 text-5xl font-bold">$7<span className="text-base font-normal text-[var(--muted)]"> / month</span></div><ul className="mt-7 space-y-3 text-[var(--muted)]"><li>✓ More AI generations</li><li>✓ Memory Studio</li><li>✓ Social content tools</li><li>✓ Advanced pet insights</li></ul><button className="btn btn-primary mt-8 w-full">Coming soon</button></div></div></section>
<footer className="bg-[var(--ink)] py-10 text-white"><div className="container flex flex-col gap-5 text-sm md:flex-row md:items-center md:justify-between"><b>🐾 PetAlyze</b><span className="text-white/60">© 2026 PetAlyze</span><div className="flex gap-5 text-white/70"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/contact">Contact</Link></div></div></footer>
</main>
}
