import Link from "next/link";
import SiteHeader from "@/components/site-header";
import ScrollReveal from "@/components/scroll-reveal";
import BeforeAfter from "@/components/before-after";
import PetTypeIcon from "@/components/pet-type-icons";

const core=[
 ["01","Профиль и паспорт","Основные данные, особенности, микрочип, вакцинации и важная информация — в одном цифровом профиле."],
 ["02","Дневник и воспоминания","Сохраняйте смешные случаи, важные события, привычки и маленькие моменты, которые хочется помнить."],
 ["03","Фото и медиатека","Соберите фотографии питомца в личной медиатеке и используйте лучшие снимки для AI-творчества."],
 ["04","Всё связано с питомцем","Истории, фотографии, паспорт и созданные AI-работы остаются рядом с профилем именно вашего питомца."],
];
const ai=[
 ["AI Story","2 кредита","История","Превратите реальное событие в персональную историю, стихотворение или текст для публикации."],
 ["AI Illustration","8 кредитов","Иллюстрация","Создавайте художественные версии фотографий, сохраняя узнаваемые черты питомца."],
 ["AI Comic","32 кредита / 4 панели","Комикс","Соберите небольшое приключение, где ваш питомец становится главным героем."],
 ["AI Video","скоро","Видео","Следующий шаг PetAlyze — короткие AI-видео из любимых фотографий и моментов."],
];
const plans=[
 {name:"Free",price:"$0",sub:"навсегда",credits:"30 AI-кредитов в месяц",pets:"1 питомец",items:["Профиль и цифровой паспорт","Дневник и воспоминания","Медиатека","AI-функции за включённые кредиты"]},
 {name:"Plus",price:"$7.99",sub:"в месяц",credits:"400 AI-кредитов в месяц",pets:"до 3 питомцев",popular:true,items:["Всё из Free","Больше AI-историй и иллюстраций","AI-комиксы","Больше творчества каждый месяц"]},
 {name:"Pro",price:"$14.99",sub:"в месяц",credits:"800 AI-кредитов в месяц",pets:"больше питомцев",items:["Всё из Plus","Вдвое больше AI-кредитов","Больше пространства для творчества","Для активного создания контента"]},
];
export default function Home(){return <main className="public-home v123">
 <ScrollReveal/><SiteHeader/>
 <section className="hero-v3"><div className="container hero-v3-grid">
  <div data-reveal><div className="eyebrow">ПАМЯТЬ • ЗАБОТА • ТВОРЧЕСТВО</div><h1>Вся жизнь вашего питомца — <span>в одном месте.</span></h1><p className="hero-copy">Храните фотографии, воспоминания, паспорт и важные события. PetAlyze помогает превращать реальные моменты в персональные истории, иллюстрации и комиксы — а следующим шагом станет AI-видео.</p><div className="hero-actions"><Link href="/signup" className="btn btn-primary">Начать бесплатно →</Link><Link href="/#showcase" className="btn btn-secondary">Посмотреть примеры</Link></div><div className="trust-row"><span>✓ Бесплатный план</span><span>✓ Карта не нужна</span><span>✓ 30 AI-кредитов ежемесячно</span></div></div>
  <div className="hero-collage-v3" data-reveal data-delay="1"><div className="float-note note-one">Реальное фото</div><img className="hero-real" src="/showcase/lubopyt-illustration-before-after.png" alt="Пример AI-иллюстрации PetAlyze: исходная фотография и результат"/><div className="float-note note-two">Фото → AI Illustration ✨</div></div>
 </div></section>

 <section id="features" className="container section-pad"><div className="section-intro" data-reveal><div className="eyebrow">БОЛЬШЕ, ЧЕМ AI-ГЕНЕРАТОР</div><h2>Один профиль. Целая жизнь рядом.</h2><p>PetAlyze объединяет то, что обычно хранится в разных местах: данные питомца, важные даты, фотографии, воспоминания и творческие работы.</p></div><div className="feature-grid">{core.map(([n,t,x],i)=><article className="feature-v2" data-reveal data-delay={String((i%2)+1)} key={n}><span>{n}</span><div><h3>{t}</h3><p>{x}</p></div></article>)}</div></section>

 <section id="showcase" className="showcase-section-v3"><div className="container section-pad"><div className="showcase-head" data-reveal><div><div className="eyebrow orange">СДЕЛАНО В PETALYZE</div><h2>От настоящего момента — к новой истории.</h2></div><p>Мы показываем реальные примеры, созданные во время разработки PetAlyze. Исходная фотография и воспоминание остаются отправной точкой для нового контента.</p></div>
 <div className="showcase-v3-grid">
  <figure className="showcase-card compare-card" data-reveal><BeforeAfter/><figcaption><b>Фото → AI Illustration</b><span>Передвигайте разделитель и сравните реальную фотографию Lubopyt с AI-иллюстрацией.</span></figcaption></figure>
  <article className="story-demo" data-reveal data-delay="1"><div className="story-demo-top"><span>AI STORY • 2 КРЕДИТА</span><b>Солнечная улыбка Lubopyt</b></div><blockquote>У окна было особенно тихо. Солнечный свет лёг на шерсть Lubopyt, и обычный домашний момент вдруг стал маленькой историей, которую хочется сохранить.</blockquote><div className="story-tags"><span>Из воспоминания</span><span>Персональная история</span></div></article>
  <figure className="showcase-card comic" data-reveal data-delay="2"><img src="/showcase/lubopyt-comic.png" alt="Четырёхпанельный AI Comic, созданный в PetAlyze"/><figcaption><b>Фото → AI Comic</b><span>Питомец становится героем последовательной визуальной истории.</span></figcaption></figure>
  <article className="video-preview" data-reveal data-delay="3"><div className="video-stage video-coming-stage"><img className="video-photo" src="/showcase/lubopyt-before.jpg" alt="Фотография Lubopyt"/><img className="video-art" src="/showcase/lubopyt-after.jpg" alt="AI-иллюстрация Lubopyt"/><span className="video-motion-line" aria-hidden="true"/><span className="coming-badge">AI VIDEO · СКОРО</span><span className="video-coming-copy">Фото + история → движение</span></div><div><b>Следующий шаг — движение.</b><p>Готовим короткие AI-видео на основе фотографий и историй питомца. Функция ещё не доступна и не входит в текущую платную услугу.</p></div></article>
 </div></div></section>

 <section id="ai-studio" className="ai-v3"><div className="container section-pad"><div className="section-intro" data-reveal><div className="eyebrow orange">PETALYZE AI STUDIO</div><h2>Один момент. Несколько способов сохранить его.</h2><p>Выберите питомца, фотографию или событие из дневника — и используйте ваш собственный контекст как отправную точку.</p></div><div className="creative-flow" data-reveal><span>▣ <b>Фото</b></span><i>→</i><span>✦ <b>История</b></span><i>→</i><span>◈ <b>Иллюстрация</b></span><i>→</i><span>▦ <b>Комикс</b></span><i>→</i><span className="coming">▶ <b>Видео</b><small>СКОРО</small></span></div><div className="ai-grid-v2">{ai.map(([t,c,label,x],i)=><article className="ai-card-v2" data-reveal data-delay={String(i+1)} key={t}><div className="ai-card-top"><span>{label}</span><em>{c}</em></div><h3>{t}</h3><p>{x}</p></article>)}</div><div className="identity-v2" data-reveal><div><span>IDENTITY REFERENCES</span><h3>ИИ ориентируется на фотографии именно вашего питомца.</h3><p>Выберите основные снимки — мордочку, профиль и полный рост. Они помогают сохранять узнаваемость питомца в новых иллюстрациях и комиксах.</p></div><div className="identity-symbol">◉ <i>→</i> ✦</div></div></div></section>

 <section className="pets-strip-v3"><div className="container pets-copy" data-reveal><div className="eyebrow">НЕ ТОЛЬКО СОБАКИ И КОШКИ</div><h2>PetAlyze — для тех, кого вы называете своим питомцем.</h2><div className="pet-types-v3"><span><i><PetTypeIcon kind="dog"/></i><b>Собаки</b></span><span><i><PetTypeIcon kind="cat"/></i><b>Кошки</b></span><span><i><PetTypeIcon kind="rabbit"/></i><b>Кролики</b></span><span><i><PetTypeIcon kind="bird"/></i><b>Птицы</b></span><span><i><PetTypeIcon kind="hamster"/></i><b>Хомяки</b></span><span><i><PetTypeIcon kind="other"/></i><b>И другие</b></span></div></div></section>

 <section id="how" className="container section-pad"><div className="section-intro center" data-reveal><div className="eyebrow">КАК ЭТО РАБОТАЕТ</div><h2>Сохраняйте жизнь. Создавайте из неё новое.</h2></div><div className="steps-v2">{[["1","Создайте профиль","Добавьте питомца и основные данные. Начать можно бесплатно и без банковской карты."],["2","Собирайте моменты","Загружайте фотографии, ведите дневник и храните важную информацию в цифровом паспорте."],["3","Творите с AI","Превращайте ваши материалы в истории, иллюстрации и комиксы. AI-видео появится следующим этапом."]].map(([n,t,x],i)=><div className="step-v2" data-reveal data-delay={String(i+1)} key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></div>)}</div></section>

 <section className="container pb-24"><div className="share-v2" data-reveal><div><div className="eyebrow orange">СОЗДАНО, ЧТОБЫ ДЕЛИТЬСЯ</div><h2>Контент, которым хочется поделиться.</h2></div><div><p>Используйте созданные истории, иллюстрации и комиксы для Instagram, TikTok, YouTube и других социальных платформ. В будущем к ним добавятся AI-видео.</p><p className="disclaimer">PetAlyze не гарантирует охват, соответствие требованиям программ монетизации или доход на сторонних платформах.</p></div></div></section>

 <section id="pricing" className="pricing-v2"><div className="container section-pad"><div className="section-intro center" data-reveal><div className="eyebrow">ПОНЯТНЫЕ ТАРИФЫ</div><h2>Начните бесплатно. Расширяйте возможности, когда будете готовы.</h2><p>Кредиты расходуются только на AI-функции. Профиль, дневник, паспорт и медиатека остаются основой PetAlyze.</p></div><div className="plans-v2">{plans.map((p,i)=><article className={`plan-v2 ${p.popular?"popular":""}`} data-reveal data-delay={String(i+1)} key={p.name}>{p.popular&&<span className="popular-label">Популярный</span>}<h3>{p.name}</h3><div className="price"><b>{p.price}</b><span>{p.sub}</span></div><div className="credit-box-v2"><b>{p.credits}</b><span>{p.pets}</span></div><div className="plan-lines">{p.items.map(x=><p key={x}>✓ {x}</p>)}</div>{p.name==="Free"?<Link href="/signup" className="btn btn-secondary mt-auto w-full">Начать бесплатно</Link>:<div className="payment-note">Платная подписка станет доступна после подключения оплаты</div>}</article>)}</div><div className="credits-note"><b>AI-кредиты:</b><span>история — 2 · иллюстрация — 8 · комикс из 4 панелей — 32. Кредиты тарифа обновляются каждый месяц и не переносятся.</span></div></div></section>

 <section className="container final-wrap"><div className="final-v2" data-reveal><img src="/brand/petalyze-icon.png" alt="PetAlyze"/><div><h2>Начните с одного настоящего момента.</h2><p>Создайте бесплатный профиль питомца. Банковская карта не требуется.</p></div><Link href="/signup" className="btn btn-primary">Создать аккаунт →</Link></div></section>
 <footer className="site-footer"><div className="container footer-v2"><div><div className="brand-lockup footer-brand"><img src="/brand/petalyze-icon.png" alt="" className="brand-icon"/><span><b className="brand-pet">Pet</b><b>Alyze</b></span></div><p>© 2026 PetAlyze · Цифровой сервис для владельцев домашних животных</p></div><div className="footer-links"><Link href="/privacy">Конфиденциальность</Link><Link href="/terms">Условия</Link><Link href="/refund">Возврат средств</Link><Link href="/contact">Контакты</Link><a href="mailto:support@petalyzeai.com">support@petalyzeai.com</a></div></div></footer>
 </main>}
