import Link from "next/link";

export const metadata = { title: "Terms of Service — PetAlyze" };

export default function TermsPage() {
  return <main className="container py-16">
    <Link href="/" className="font-bold text-[var(--green)]">← PetAlyze</Link>
    <article className="card mt-8 max-w-4xl p-8 md:p-10">
      <h1 className="text-4xl font-bold">Terms of Service</h1>
      <p className="mt-3 text-sm text-[var(--muted)]">Effective: September 5, 2026</p>
      <div className="mt-8 space-y-8 leading-7 text-[var(--muted)]">
        <section><h2 className="text-xl font-bold text-[var(--ink)]">1. PetAlyze service</h2><p className="mt-2">PetAlyze is a digital service for pet owners. Features may include pet profiles, journals, digital pet passport records, media storage and AI-assisted stories, illustrations, comics and other creative tools. PetAlyze does not sell physical goods through these services.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">2. Accounts</h2><p className="mt-2">You are responsible for providing accurate account information, keeping your credentials secure and for activity performed through your account. You must use the service lawfully and must not attempt to interfere with, reverse engineer, abuse or gain unauthorized access to PetAlyze or other users' information.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">3. Pet information is not veterinary advice</h2><p className="mt-2">PetAlyze journal, passport, reminders, AI outputs and other content are organizational or creative tools and are not veterinary diagnosis, treatment or professional medical advice. For health concerns, contact a qualified veterinarian.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">4. Your content</h2><p className="mt-2">You retain your rights in photos, text and other content you upload. You give PetAlyze a limited permission to host, process, reproduce and transform that content only as reasonably necessary to operate the service and provide features you request. You represent that you have the rights needed to upload and use the content.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">5. AI-generated content</h2><p className="mt-2">AI outputs can be inaccurate, unexpected or similar to outputs generated for others. You are responsible for reviewing generated content before relying on, publishing or commercializing it. PetAlyze does not guarantee uniqueness, intellectual-property protection, social-platform eligibility, reach or earnings.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">6. Plans, credits and subscriptions</h2><p className="mt-2">PetAlyze may offer Free, Plus and Pro plans. AI features consume credits according to the credit cost shown in the service. Included subscription credits are allocated for the applicable credit period and do not roll over unless PetAlyze expressly states otherwise. Purchased credit packs, if introduced, may have separate terms.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">7. Paid services</h2><p className="mt-2">When paid checkout becomes available, the price, currency and billing interval will be shown before purchase. Recurring subscriptions renew according to the selected monthly or annual billing interval until canceled, subject to the cancellation terms shown at purchase. Taxes or payment-provider charges may apply where required. Current refund rules are described in our <Link href="/refund" className="font-semibold text-[var(--green)] underline">Refund Policy</Link>.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">8. Technical failures and credits</h2><p className="mt-2">AI generation depends on third-party infrastructure and may occasionally fail. Where PetAlyze records a technical generation failure after credits were charged, we may automatically restore the applicable credits. Reports about unsatisfactory but technically completed outputs may be reviewed separately.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">9. Availability and changes</h2><p className="mt-2">We may modify, add, suspend or discontinue features as the service evolves. We aim to provide a reliable service but do not guarantee uninterrupted or error-free availability.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">10. Suspension and termination</h2><p className="mt-2">We may restrict or terminate access where reasonably necessary for security, fraud prevention, unlawful activity, material violation of these Terms or protection of the service and its users. You may stop using PetAlyze at any time.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">11. Disclaimers and liability</h2><p className="mt-2">To the extent permitted by applicable law, PetAlyze is provided on an “as available” basis without guarantees about specific creative, commercial or third-party-platform results. Nothing in these Terms excludes rights or liabilities that cannot legally be excluded.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">12. Changes to these Terms</h2><p className="mt-2">We may update these Terms as the product, pricing or legal requirements change. The effective date above identifies the current version. Continued use after an applicable update means the updated Terms govern future use, subject to rights provided by law.</p></section>
        <section><h2 className="text-xl font-bold text-[var(--ink)]">13. Contact</h2><p className="mt-2">Questions about these Terms can be sent through our <Link href="/contact" className="font-semibold text-[var(--green)] underline">Contact page</Link>.</p></section>
      </div>
    </article>
  </main>;
}
